### ISSUE TITLE
override the .local directory

### ISSUE THREAD

**Issue by asemoon** [curist/grunt-bower#62]
I am running a Sails app on Openshift. grunt-bower uses ~/.local to save bower data, however, on some platforms like openshift the home directory is not writable. Is there a way to override the .local directory when setting up grunt-bower?

I have tried renaming the HOME directory before running the app, and overriding the following env variables with writable directories, however, grunt-bower seems to be ignoring these and still keeps using ~/.local and therefor sails deployment fails. 
`XDG_DATA_HOME
XDG_CONFIG_HOME`

**Comment by curist** [comment]
In general, this shouldn't be an issue at all.

Grunt is meant for development, and `grunt-bower` is for bundling your app
for deployment.

And to my knowledge, it's `bower` using `~/.local`; so if you're looking
for overriding anything, please check `bower`'s document.

Care to elaborate more about the use case?


Mehdi Karamenjad <notifications@github.com> 於 2016年6月21日 週二 下午2:13寫道：

**Comment by asemoon** [comment]
Thanks for the response, yeah I dug a little deeper and found the right place to override `XDG_DATA_HOME, XDG_CONFIG_HOME`  and it did work. I am using Openshift online as Pass and per their policy ~/.local is locked down for write. After going through grunt-bower code and the following link + hours of headache, It was fixed. 

[https://github.com/Waxolunist/christian.sterzl.info/blob/master/resources/content/blog/bower-on-openshift.md](url)
